(() => {
  const base='https://wulikeshihua-1339740714.cos.ap-beijing.myqcloud.com/%E8%AF%AD%E6%96%87/assets/media/journey/lessons/', key=`${base}xiyouji_13_key_shots/`, old=`${base}xiyouji_06_portraits/`, portrait=`${base}xiyouji_13_portraits/`;
  document.title='小雷音寺降黄眉 · 名著精学'; document.body.style.background=`linear-gradient(135deg,rgba(10,25,28,.55),rgba(4,10,12,.78)),url('${key}01-mountain-temple.png') center/cover fixed`; document.querySelector('.eyebrow').textContent='西游记 · 第 65—66 回 · 名著精学'; document.querySelector('h1').textContent='小雷音寺降黄眉'; document.getElementById('story-video-trigger').style.display='none'; document.getElementById('story-video-modal').hidden=true;
  const tabs=[...document.querySelectorAll('.tabs button')], topics=[...document.querySelectorAll('.topic')], open=id=>{topics.forEach(x=>x.classList.toggle('is-active',x.id===id));tabs.forEach(x=>x.classList.toggle('is-active',x.dataset.topic===id))};tabs.forEach(x=>x.onclick=()=>open(x.dataset.topic));
  const pages=[['假寺诱入','师徒来到一座庄严佛寺，唐僧见佛便拜，却不知这是黄眉怪假设的小雷音寺。','假寺最重要的考点是“以真乱假”：外表像佛门，内里却是妖怪设局。唐僧的虔诚被利用，悟空的警觉才显出价值。'],['金铙困猿','黄眉怪现出本相，用金铙扣住悟空，又以人种袋收去兵器、困住众人。','金铙和人种袋不是普通武器，它们使悟空不能硬拼，故事因此转入破法宝、求智慧的阶段。'],['求援受挫','悟空请来天兵神将相助，法宝仍能收走来敌兵器，外援也一时无功。','写援兵受挫，是为了说明黄眉法宝厉害，并逼悟空继续寻找对方的弱点，而不是简单堆叠神仙。'],['悟空变策','悟空暗中周旋，变化试探，终于夺回人种袋；黄眉仍想逃脱，局面转向弥勒布置的瓜田。','悟空的胜利来自观察、试探和变通。面对法宝困局，先找规律再设法破局，才是人物分析的关键证据。'],['弥勒收伏','弥勒佛设瓜田诱黄眉弯腰，收回法宝，指出黄眉本是自己座前童子。师徒获救，重上西路。','结局同时回答身份和因果：黄眉不是佛，弥勒才是真正的主人；收伏后师徒继续西行，假寺风波完整收束。']];
  const reading=document.getElementById('reading'), img=reading.querySelector('.scene-image-frame img');img.src=`${base}xiyouji_13_reading_storyboard.png`;img.alt='小雷音寺降黄眉五幕连环图';const copy=reading.querySelector('.reading-copy');copy.innerHTML='<div class="reading-pager-top"><div class="reading-mode-switch"><button class="is-active" data-mode="both">对照</button><button data-mode="old">原文</button><button data-mode="new">白话</button></div><span class="reading-progress"></span></div><section class="reading-page"></section><div class="reading-pager-bottom"><button class="reading-nav" data-move="-1">←</button><div class="reading-stage-dots"></div><button class="reading-nav" data-move="1">→</button></div>';let p=0,m='both';const read=()=>{let [t,a,b]=pages[p],h=[];if(m!=='new')h.push(`<article class="reading-panel"><h3>情节原貌 · ${t}</h3><p>${a}</p></article>`);if(m!=='old')h.push(`<article class="reading-panel"><h3>白话精读 · ${t}</h3><p>${b}</p></article>`);copy.querySelector('.reading-page').innerHTML=h.join('');copy.querySelector('.reading-progress').textContent=`${String(p+1).padStart(2,'0')} / 05`;copy.querySelector('.reading-stage-dots').innerHTML=pages.map((x,i)=>`<button class="reading-stage-dot${i===p?' is-active':''}" data-page="${i}" title="${x[0]}"></button>`).join('')};copy.onclick=e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.mode)m=b.dataset.mode;if(b.dataset.page!==undefined)p=+b.dataset.page;if(b.dataset.move)p=Math.max(0,Math.min(4,p+(+b.dataset.move)));read()};read();
  const scenes=[['假寺入山','01-mountain-temple'],['黄眉扮佛','02-yellow-brow-fake-buddha'],['师徒入寺','03-team-enters-temple'],['金铙困猿','04-golden-cymbals-trap'],['悟空脱困','05-wukong-escapes-cymbals'],['人种袋收敌','06-human-seed-bag'],['师徒被困','07-team-captured'],['悟空求援','08-wukong-seeks-help'],['援兵受挫','09-heavenly-help-fails'],['悟空变策','10-wukong-changes-tactics'],['变化试探','11-wukong-becomes-watermelon'],['黄眉失察','12-yellow-brow-confused'],['夺回法宝','13-magic-bag-recovered'],['弥勒设局','14-millet-field-trap'],['黄眉入局','15-yellow-brow-eats-millet'],['弥勒到来','16-maitreya-arrives'],['童子现形','17-yellow-brow-revealed'],['弥勒收伏','18-maitreya-subdues'],['师徒获救','19-team-freed'],['重上西路','20-westward-resumes']];
  const notes=['假寺外貌庄严，专门利用唐僧的虔诚把师徒诱入险境。','黄眉假扮佛祖，点明本回“真假佛寺”的核心冲突。','唐僧拜佛、悟空警觉，师徒的不同判断推动危机出现。','金铙扣住悟空，法宝困局由此开始。','悟空先逃出金铙，说明他不会困在一次失败里。','人种袋收走兵器，危机从个人扩大到整个队伍。','唐僧和弟子被困，救师任务再次成为主线。','悟空求援，是在法宝无法硬破后的策略变化。','援兵受挫，反衬人种袋的特殊威力。','悟空不再盲目加人，而是转向观察法宝弱点。','变化试探，是悟空以智破局的证据。','黄眉误以为悟空已无计可施，警惕下降。','悟空夺回人种袋，法宝困局开始扭转。','弥勒布下瓜田，为收伏黄眉创造条件。','黄眉贪食入局，假佛终于露出破绽。','弥勒到来，真正的主人进入故事。','黄眉被揭为弥勒座前童子，真假彻底分明。','弥勒收回法宝，完成因果收束。','师徒获救，假寺造成的危机解除。','队伍重新上路，回到取经主线。'];
  const groups=[['fake','01 假寺诱入','从寺外初见到悟空脱困：假寺像真寺，唐僧被虔诚驱动，悟空的警觉成为第一处对照。'],['trapped','02 法宝困局','从人种袋收敌到援兵受挫：两件法宝连续困敌，悟空不能再用单纯硬拼。'],['turn','03 悟空变策','从观察法宝到黄眉入局：援兵受挫后，悟空以试探、变化和夺袋找回主动权。'],['maitreya','04 弥勒收伏','从弥勒到来到重上西路：主人收回法宝，真假分明，师徒获救西行。']];
  const groupFor=i=>i<5?'fake':i<10?'trapped':i<15?'turn':'maitreya';
  const plot=document.getElementById('plot');plot.innerHTML='<div class="story-groups"></div><div class="plot-layout"><div class="scene-art"><img></div><article class="scene-copy"><div class="group-detail"></div><h3></h3><p></p><ul></ul></article></div><div class="scene-selector"></div>';let activeGroup='fake';
  const show=i=>{let s=scenes[i],n=notes[i],image=plot.querySelector('.scene-art img');image.src=`${key}${s[1]}.png`;image.alt=s[0];plot.querySelector('h3').textContent=s[0];plot.querySelector('.scene-copy p').textContent=n;plot.querySelector('.scene-copy ul').innerHTML=`<li><b class="highlight">情节作用：</b>${n}</li><li><b class="highlight">人物关系：</b>悟空辨真破局，唐僧与师弟们的安危始终是行动目标。</li><li><b class="highlight">中考方向：</b>概括时写清法宝困局、策略变化或弥勒收伏的因果。</li>`;plot.querySelectorAll('[data-scene]').forEach(x=>x.classList.toggle('is-active',+x.dataset.scene===i))};
  const renderPlot=()=>{let group=groups.find(x=>x[0]===activeGroup),list=scenes.map((s,i)=>({s,i})).filter(x=>groupFor(x.i)===activeGroup);plot.querySelector('.story-groups').innerHTML=groups.map(x=>`<button class="${x[0]===activeGroup?'is-active':''}" data-group="${x[0]}"><b>${x[1]}</b></button>`).join('');plot.querySelector('.group-detail').textContent=group[2];plot.querySelector('.scene-selector').innerHTML=list.map(({s,i})=>`<button data-scene="${i}"><span>${String(i+1).padStart(2,'0')} / 20</span><b>${s[0]}</b></button>`).join('');show(list[0].i)};
  plot.onclick=e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.group){activeGroup=b.dataset.group;renderPlot()}else if(b.dataset.scene!==undefined)show(+b.dataset.scene)};renderPlot();
  const card=(src,n,r,t,d)=>`<article class="person"><div class="portrait"><img src="${src}" alt="${n}人物群像"></div><div class="person-copy"><p class="person-role"><b>${n}</b><span>${r}</span></p><div class="traits">${t}</div><p>${d}</p></div></article>`;
  document.getElementById('people').innerHTML=`<div class="relationship-map"><article class="relationship-card"><span>真假冲突</span><b>黄眉 × 小雷音寺</b><p>他以假寺、假佛利用唐僧的虔诚，让“所见”成为陷阱。</p></article><article class="relationship-card core"><span>破局主线</span><b>悟空 × 金铙人种袋</b><p>法宝不能硬破，悟空从试探规律到夺回法宝，完成策略转折。</p></article><article class="relationship-card"><span>因果收束</span><b>弥勒 × 黄眉童子</b><p>主人设瓜田收伏座前童子，揭开假佛身份并收回法宝。</p></article></div><div class="people-grid">${card(`${old}sun-wukong.png`,'孙悟空','破局者 · 应变者','<span class="trait-core">机智担当</span><span class="trait-action">试探变策</span>','面对金铙、人种袋不硬拼到底，转而观察、变化、夺回法宝，体现<b class="highlight">善于应变</b>。')}${card(`${old}tang-sanzang.png`,'唐三藏','取经人 · 被迷惑者','<span class="trait-core">虔诚善良</span><span class="trait-flaw">易信表象</span>','他见佛便拜，虔诚被假寺利用；这一判断反衬悟空辨真的必要。')}${card(`${old}zhu-bajie.png`,'猪八戒','同伴 · 受困者','<span class="trait-core">忠于师父</span><span class="trait-action">同陷危机</span>','他与师父、沙僧一同被困，使悟空的行动始终指向救回整支队伍。')}${card(`${portrait}yellow-brow-demon.png`,'黄眉怪','假佛者 · 设局者','<span class="trait-flaw">善于伪装</span><span class="trait-action">金铙人种袋</span>','他假设小雷音寺，又凭两件法宝制造困局；人物分析要写清<b class="highlight">假象与法宝</b>两层手段。')}${card(`${portrait}maitreya.png`,'弥勒佛','收伏者 · 解局者','<span class="trait-core">明察从容</span><span class="trait-action">瓜田设局</span>','他不靠正面硬斗，而是以瓜田诱黄眉弯腰，收回法宝并点明童子身份。')}</div>`;

  const exam=document.getElementById('exam');
  exam.innerHTML='<div class="exam-grid"><article class="exam-card answer-card"><h3>情节题答案搭建器</h3><div class="answer-builder"><div class="answer-step"><span>01 起因</span><b>假寺诱入</b><p>先交代假象如何出现。</p></div><div class="answer-step"><span>02 困局</span><b>法宝困敌</b><p>写清金铙与人种袋。</p></div><div class="answer-step"><span>03 变策</span><b>试探破局</b><p>突出悟空不硬拼。</p></div><div class="answer-step"><span>04 收束</span><b>弥勒收童</b><p>补足身份与西行。</p></div></div><p class="formula"><b>完整答案：</b>黄眉怪假设小雷音寺，把虔诚的唐僧师徒诱入寺中，又用金铙、人种袋困住悟空和众人；悟空多方求援受挫后转而观察、试探，终于扭转法宝困局；弥勒佛以瓜田设局，收伏座前黄眉童子、收回法宝，师徒获救后继续西行。</p><div class="answer-evidence"><section class="evidence-board"><h4>把答案写实：三处证据定位</h4><div class="evidence-list"><div><b>假寺诱入</b><span>寺貌庄严、黄眉假扮佛祖，唐僧因虔诚拜佛而失去警觉。</span></div><div><b>法宝受挫</b><span>金铙困悟空、人种袋收兵器，连援兵也一时难以硬破。</span></div><div><b>瓜田收伏</b><span>弥勒诱黄眉弯腰入局，收回法宝并说明其座前童子的身份。</span></div></div></section><aside class="answer-checklist"><h4>落笔前自检</h4><p>交代假寺与假佛</p><p>写清两件法宝</p><p>突出悟空策略变化</p><p>补足弥勒收伏西行</p></aside></div></article><article class="exam-card avoid-card"><h3>高频题与易失分</h3><div class="exam-types"><div class="exam-type"><b>情节概括</b><p>不能只写“降黄眉”，要写假寺诱入、法宝困局、变策、收伏的因果链。</p></div><div class="exam-type"><b>人物形象</b><p>悟空的机智体现在援兵受挫后仍能观察、试探和变通。</p></div><div class="exam-type"><b>真假辨析</b><p>小雷音寺和黄眉佛像都是假象；弥勒佛才是真正的主人。</p></div><div class="exam-type"><b>作用分析</b><p>金铙、人种袋迫使故事从硬拼转向破法宝、找规律。</p></div></div><ul><li>黄眉怪是假佛，小雷音寺是假寺，不能把二者误写成真佛门考验。</li><li>最终收伏黄眉的是弥勒佛；悟空的重要作用是不断试探并创造破局条件。</li><li>瓜田设局不是普通斗法，它解释了为什么黄眉会失去防备、现出童子身份。</li></ul><div class="exam-review"><section class="review-item"><span>考场 30 秒</span><b>先定因果</b><p>假寺诱入，法宝困敌，变策破局，弥勒收伏。</p></section><section class="review-item"><span>答题核心</span><b>策略在前</b><p>用求援受挫、试探变化证明悟空善应变。</p></section><section class="review-item"><span>最后检查</span><b>真假写准</b><p>黄眉是假佛，弥勒是主人，师徒最后重上西路。</p></section></div></article></div>';

  const questions=[['情节顺序','下列哪一项最符合“小雷音寺降黄眉”的因果链？',['假寺诱入—法宝困敌—悟空变策—弥勒收伏—师徒西行','弥勒收伏—假寺诱入—悟空放弃救师','人种袋失效—黄眉逃走—唐僧独自西行','悟空先收伏黄眉—弥勒再借法宝'],0,'要抓住假象、困局、变策、收束四个阶段。','plot','回到关键镜头'],['人物理解','孙悟空在法宝困局中的做法最能表现什么？',['只会硬拼','援兵受挫后仍观察、试探并调整策略','害怕黄眉而离开','依靠唐僧识破假寺'],1,'悟空的机智在于从硬破无效转向寻找法宝弱点。','people','回到人物群像'],['真假辨析','下列说法正确的是？',['黄眉怪是真佛祖','小雷音寺是真寺院','弥勒佛是黄眉的主人，最终收回法宝','唐僧用金铙收伏黄眉'],2,'假寺和假佛是本回核心冲突，弥勒佛才是真正的主人。','exam','回到中考攻略'],['情节作用','人种袋、金铙在故事中的作用是？',['让悟空轻易取胜','制造不能硬破的困局，推动悟空改变策略','帮助师徒直接西行','只用于装饰假寺'],1,'两件法宝让援兵也受挫，迫使悟空从斗力转向斗智。','plot','回到关键镜头'],['简答框架','概括本回时最完整的写法是？',['只写黄眉被弥勒带走','假寺诱入—法宝困敌—悟空变策—弥勒收童—师徒西行','只写悟空和黄眉打斗','只写师徒继续赶路'],1,'情节概括要写清假象、法宝、策略转折和最后因果。','exam','回到中考攻略']];
  const qImages=['01-mountain-temple.png','10-wukong-changes-tactics.png','17-yellow-brow-revealed.png','06-human-seed-bag.png','20-westward-resumes.png'];
  const qtabs=document.getElementById('question-tabs'),stem=document.getElementById('stem'),options=document.getElementById('options'),feedback=document.getElementById('feedback'),review=document.getElementById('review-link'),progress=document.getElementById('question-progress'),layout=document.querySelector('.question-layout');
  document.querySelector('#practice .question-side p').textContent='围绕假寺、法宝、人物判断和情节因果，检验本回学习成果。';
  document.querySelector('#practice .question-main h3').textContent='《小雷音寺降黄眉》自测';
  const showQuestion=i=>{const q=questions[i];stem.textContent=q[1];layout.style.backgroundImage=`url('${key}${qImages[i]}')`;layout.style.backgroundSize='cover';layout.style.backgroundPosition='center';options.replaceChildren(...q[2].map((text,index)=>{const button=document.createElement('button');button.type='button';button.innerHTML=`<span class="opt-letter">${String.fromCharCode(65+index)}</span><span class="opt-text">${text}</span>`;button.onclick=()=>{[...options.children].forEach(item=>item.classList.remove('is-selected','is-correct','is-wrong'));const correct=index===q[3];button.classList.add('is-selected',correct?'is-correct':'is-wrong');feedback.textContent=`${correct?'回答正确。':'再想一想。'}${q[4]}`;review.classList.toggle('is-visible',!correct);if(!correct){review.textContent=q[6];review.onclick=()=>open(q[5]);}};return button;}));progress.textContent=`第 ${i+1} / ${questions.length} 题`;[...qtabs.children].forEach((button,index)=>button.classList.toggle('is-active',index===i));feedback.textContent='选择一个选项后查看解析。';review.classList.remove('is-visible');};
  qtabs.replaceChildren();questions.forEach((q,index)=>{const button=document.createElement('button');button.type='button';button.textContent=`${String(index+1).padStart(2,'0')} ${q[0]}`;button.onclick=()=>showQuestion(index);qtabs.appendChild(button);});showQuestion(0);
})();
