(() => {
  const base = 'https://wulikeshihua-1339740714.cos.ap-beijing.myqcloud.com/%E8%AF%AD%E6%96%87/assets/media/journey/lessons/';
  const keyBase = `${base}xiyouji_10_key_shots/`;
  document.title = '女儿国与蝎子精 · 名著精学';
  document.body.style.background = `linear-gradient(135deg,rgba(10,25,28,.55),rgba(4,10,12,.78)),url('${keyBase}10-scorpion-observes.png') center/cover no-repeat fixed`;
  document.querySelector('.eyebrow').textContent = '西游记 · 第 54—55 回 · 名著精学';
  document.querySelector('h1').textContent = '女儿国与蝎子精';
  document.getElementById('story-video-trigger').style.display = 'none';
  document.getElementById('story-video-modal').hidden = true;
  const tabs = [...document.querySelectorAll('.tabs button')], topics = [...document.querySelectorAll('.topic')];
  const openTopic = id => { topics.forEach(x => x.classList.toggle('is-active', x.id === id)); tabs.forEach(x => x.classList.toggle('is-active', x.dataset.topic === id)); };
  tabs.forEach(x => x.addEventListener('click', () => openTopic(x.dataset.topic)));

  const pages = [
    ['子母河奇遇','师徒到了西梁女国，八戒、沙僧误饮子母河水，腹中有了胎气。悟空急寻解阳山落胎泉。','先用“误饮河水”制造反常处境，再写悟空寻泉解困。它不是主线爱情故事，而是进入女儿国前的奇异关口。'],
    ['女王相见','女王见唐僧仪容出众，命人迎入宫中，愿以国相待，又欲留他成亲。','女王的挽留真诚而克制，考验唐僧是否能在尊重他人的同时守住取经使命。'],
    ['守志辞别','唐僧合掌陈说西行大愿，不以富贵和情意改变初心。悟空等人暗中安排出城。','唐僧拒绝并非轻慢女王，而是把个人情感放在取经使命之后，体现“慈悲而坚定”的复杂形象。'],
    ['琵琶洞救师','蝎子精在路旁掳走唐僧，悟空、八戒救师时又被倒马毒桩所困。','妖精的毒刺使悟空不能只靠硬拼，故事由“救师”转到“识法门、求外援”。'],
    ['昴日除妖','悟空请来昴日星官，鸡鸣之威正克蝎子精。妖精现原形而死，唐僧获救，师徒重上西路。','结局写出相克之理与团队协作：知道何人能破局，和勇敢出战一样重要。'],
  ];
  const reading = document.getElementById('reading');
  reading.querySelector('.scene-image-frame img').src = `${base}xiyouji_10_reading_storyboard.png`;
  reading.querySelector('.scene-image-frame img').alt = '女儿国与蝎子精五幕连环图';
  const copy = reading.querySelector('.reading-copy');
  copy.innerHTML = '<div class="reading-pager-top"><div class="reading-mode-switch"><button class="is-active" data-mode="both">对照</button><button data-mode="old">原文</button><button data-mode="new">白话</button></div><span class="reading-progress"></span></div><section class="reading-page"></section><div class="reading-pager-bottom"><button class="reading-nav" data-move="-1">←</button><div class="reading-stage-dots"></div><button class="reading-nav" data-move="1">→</button></div>';
  let pi = 0, mode = 'both';
  const renderRead = () => { const [t,o,n] = pages[pi], blocks=[]; if(mode !== 'new') blocks.push(`<article class="reading-panel"><h3>原文节选 · ${t}</h3><p>${o}</p></article>`); if(mode !== 'old') blocks.push(`<article class="reading-panel"><h3>白话精读 · ${t}</h3><p>${n}</p></article>`); copy.querySelector('.reading-page').innerHTML=blocks.join(''); copy.querySelector('.reading-page').classList.toggle('is-single',blocks.length===1); copy.querySelector('.reading-progress').textContent=`${String(pi+1).padStart(2,'0')} / 05`; copy.querySelector('.reading-stage-dots').innerHTML=pages.map((x,i)=>`<button class="reading-stage-dot${i===pi?' is-active':''}" data-page="${i}" title="${x[0]}"></button>`).join(''); copy.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('is-active',x.dataset.mode===mode)); copy.querySelectorAll('[data-move]').forEach(x=>x.disabled=(Number(x.dataset.move)<0&&pi===0)||(Number(x.dataset.move)>0&&pi===4)); };
  copy.addEventListener('click', e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.mode)mode=b.dataset.mode;if(b.dataset.page!==undefined)pi=Number(b.dataset.page);if(b.dataset.move)pi=Math.max(0,Math.min(4,pi+Number(b.dataset.move)));renderRead();}); renderRead();

  const groups=[['river','01 奇河入国','河水奇遇与女儿国相见，交代反常世界和故事的第一层考验。'],['choice','02 女王挽留','情感与使命并置，唐僧的选择推动师徒离开女儿国。'],['cave','03 蝎洞救师','蝎子精掳师、毒桩难破，悟空必须改变救援策略。'],['ending','04 请星除妖','昴日星官相克降妖，救师完成并回到西行主线。']];
  const scenes=[
    ['river','子母河畔','师徒临水而行','01-river-arrival','环境奇异，预示非常遭遇。'],['river','误饮河水','八戒不慎饮水','02-river-water','奇异设定制造行动难题。'],['river','腹中有胎','师徒急寻解法','03-unexpected-pregnancy','悟空承担寻泉解困任务。'],['river','女国城门','进入女儿国','04-women-kingdom-gate','故事由奇遇转入人情考验。'],
    ['choice','宫中初见','女王礼迎唐僧','05-queen-first-meeting','女王以国礼相待。'],['choice','倾心相问','女王听取西行志','06-queen-listens','情感与理想正面相遇。'],['choice','朝堂议亲','婚仪与富贵诱惑','07-marriage-proposal','考验唐僧取经意志。'],['choice','守志辞让','唐僧不改西行愿','08-pilgrimage-choice','慈悲而坚定的证据。'],['choice','城门惜别','女王目送师徒','09-palace-farewell','情节收束而不贬低真情。'],
    ['cave','蝎妖窥伺','妖精暗中观察','10-scorpion-observes','新的危机埋下伏笔。'],['cave','妖风掳师','唐僧被卷入洞中','11-purple-wind-capture','救师任务再度开启。'],['cave','琵琶洞困','师父暂困妖洞','12-pipa-cave-captive','明确救援目标。'],['cave','悟空救师','金箍棒斗蝎妖','13-wukong-rescue','悟空勇于担当。'],['cave','毒桩难破','倒马毒桩伤敌','14-scorpion-sting','硬拼受挫，策略转折。'],['cave','八戒助战','师兄弟并肩救师','15-bajie-joins','团队协作仍需找对方法。'],
    ['ending','求助昴日','悟空请星官破局','16-seek-rooster-lord','审时度势，善借外援。'],['ending','星官降临','昴日星官到洞前','17-rooster-lord-descends','相克之力出现。'],['ending','蝎妖现形','妖精难逃本相','18-scorpion-true-form','邪术被真正克星拆穿。'],['ending','师父获救','师徒洞前重聚','19-master-rescued','救援主线圆满。'],['ending','再上西行','四众继续赶路','20-westward-departure','回归取经大业。']];
  const plot=document.getElementById('plot'); plot.innerHTML='<div class="story-groups"></div><div class="plot-layout"><div class="scene-art"><img></div><article class="scene-copy"><div class="group-detail"></div><h3></h3><p></p><ul></ul></article></div><div class="scene-selector"></div>';
  let group='river'; const show=i=>{const s=scenes[i];plot.querySelector('.scene-art img').src=`${keyBase}${s[3]}.png`;plot.querySelector('.scene-art img').alt=s[2];plot.querySelector('h3').textContent=s[2];plot.querySelector('.scene-copy p').textContent=s[4];plot.querySelector('ul').innerHTML=`<li><b class="highlight">情节作用：</b>${s[4]}</li><li><b class="highlight">人物关系：</b>围绕唐僧取经与师徒救援展开。</li><li><b class="highlight">中考方向：</b>概括情节并写清因果。</li>`;plot.querySelectorAll('[data-scene]').forEach(b=>b.classList.toggle('is-active',Number(b.dataset.scene)===i));}; const render=()=>{const g=groups.find(x=>x[0]===group), list=scenes.map((s,i)=>({s,i})).filter(x=>x.s[0]===group);plot.querySelector('.story-groups').innerHTML=groups.map(x=>`<button class="${x[0]===group?'is-active':''}" data-group="${x[0]}"><b>${x[1]}</b></button>`).join('');plot.querySelector('.group-detail').textContent=g[2];plot.querySelector('.scene-selector').innerHTML=list.map(({s,i})=>`<button data-scene="${i}"><span>${String(i+1).padStart(2,'0')} / 20</span><b>${s[1]}</b></button>`).join('');show(list[0].i);};plot.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.group){group=b.dataset.group;render();}else if(b.dataset.scene!==undefined)show(Number(b.dataset.scene));});render();

  const legacyPortraitBase = `${base}xiyouji_06_portraits/`, portraitBase = `${base}xiyouji_10_portraits/`;
  const people=document.getElementById('people'); const card=(src,n,r,t,c)=>`<article class="person"><div class="portrait"><img src="${src}" alt="${n}人物群像"></div><div class="person-copy"><p class="person-role"><b>${n}</b><span>${r}</span></p><div class="traits">${t}</div><p>${c}</p></div></article>`; people.innerHTML=`<div class="relationship-map"><article class="relationship-card"><span>情感考验</span><b>女王 × 唐僧</b><p>真诚相待与西行使命之间，需要尊重而坚定的回应。</p></article><article class="relationship-card core"><span>救师主线</span><b>悟空 × 蝎子精</b><p>毒桩难破，悟空由迎战转向请星官破局。</p></article><article class="relationship-card"><span>团队回归</span><b>师徒 × 西行愿</b><p>每次诱惑与危机后，队伍重新回到取经目标。</p></article></div><div class="people-grid">${card(`${legacyPortraitBase}tang-sanzang.png`,'唐三藏','取经人 · 守志者','<span class="trait-core">慈悲</span><span class="trait-core">坚定</span>','面对女王挽留仍守西行愿。')}${card(`${legacyPortraitBase}sun-wukong.png`,'孙悟空','救师者 · 应变者','<span class="trait-core">担当</span><span class="trait-action">求援</span>','毒桩难破时及时请昴日星官。')}${card(`${legacyPortraitBase}zhu-bajie.png`,'猪八戒','同伴 · 助战者','<span class="trait-core">忠于师父</span><span class="trait-action">协力救师</span>','在琵琶洞外与悟空并肩救师，体现队伍协作。')}${card(`${portraitBase}women-kingdom-queen.png`,'女儿国王','相待者 · 试炼者','<span class="trait-core">真诚</span><span class="trait-action">挽留</span>','她让唐僧的选择更显使命重量。')}${card(`${portraitBase}scorpion-demon.png`,'蝎子精','掳师者 · 毒桩者','<span class="trait-flaw">凶险</span><span class="trait-action">倒马毒桩</span>','用毒桩制造不能硬破的困局。')}</div>`;
  document.getElementById('exam').innerHTML='<div class="exam-grid"><article class="exam-card answer-card"><h3>人物题答案搭建器</h3><div class="answer-builder"><div class="answer-step"><span>01 情境</span><b>女王挽留</b><p>先点出考验。</p></div><div class="answer-step"><span>02 行为</span><b>守西行愿</b><p>写具体选择。</p></div><div class="answer-step"><span>03 特点</span><b>慈悲坚定</b><p>由行为归纳。</p></div><div class="answer-step"><span>04 结果</span><b>继续西行</b><p>补足情节结果。</p></div></div><p class="formula"><b>完整答案：</b>唐僧面对女儿国王真诚挽留，仍以取经大愿为重，表现出慈悲而坚定的品质；他尊重女王的情意，却没有改变西行使命，最终带领师徒继续赶路。</p></article><article class="exam-card avoid-card"><h3>高频题与易失分</h3><div class="exam-types"><div class="exam-type"><b>人物理解</b><p>唐僧拒绝不等于冷漠，要写慈悲与使命并存。</p></div><div class="exam-type"><b>情节作用</b><p>毒桩迫使悟空改变策略、求助星官。</p></div><div class="exam-type"><b>结局因果</b><p>昴日星官是蝎子精的克星。</p></div><div class="exam-type"><b>结构线索</b><p>诱惑、掳师、受挫、求援、降妖。</p></div></div></article></div>';
  document.querySelector('.answer-card').insertAdjacentHTML('beforeend', '<div class="answer-evidence"><section class="evidence-board"><h4>把答案写实：三处证据定位</h4><div class="evidence-list"><div><b>真诚相待</b><span>女王以国礼相迎、表达挽留，先写清情境并非简单诱惑。</span></div><div><b>守住使命</b><span>唐僧合掌说明西行大愿，尊重情意却不改变取经目标。</span></div><div><b>团队西行</b><span>师徒离开女儿国、再遇蝎妖仍协力救师，体现目标始终不变。</span></div></div></section><aside class="answer-checklist"><h4>落笔前自检</h4><p>写清面对谁的挽留</p><p>交代具体回应行为</p><p>概括慈悲与坚定</p><p>补足继续西行结果</p></aside></div>');
  document.querySelector('.avoid-card').insertAdjacentHTML('beforeend', '<ul><li>女儿国王的挽留是真诚相待，不能把唐僧的拒绝写成冷漠无情。</li><li>蝎子精的倒马毒桩不是普通兵器；它使悟空必须从硬拼转向求援。</li><li>昴日星官降伏蝎妖要写出“相克破局”，不能只笼统说神仙法力大。</li></ul><div class="exam-review"><section class="review-item"><span>考场 30 秒</span><b>先定题型</b><p>人物、作用、概括、主题的落笔顺序不同。</p></section><section class="review-item"><span>答题核心</span><b>证据在前</b><p>先写女王挽留或悟空求援，再提炼人物特点。</p></section><section class="review-item"><span>最后检查</span><b>因果写全</b><p>写清为何受挫、如何破局、结果怎样回到西行。</p></section></div>');
  const qs=[['情节顺序','本回主线顺序是？',['子母河奇遇—女王挽留—蝎妖掳师—求助星官—师徒西行','蝎妖降伏—女王挽留—误饮河水','女王掳师—悟空求雨—星官辞别','真假悟空—蝎妖掳师—子母河'],0,'先写女儿国的奇遇与选择，后写蝎妖救师。','plot','回到关键镜头'],['人物理解','唐僧面对女王挽留最能表现什么？',['轻视女王','慈悲而坚定地守住使命','贪图富贵','放弃取经'],1,'要同时写出他尊重情意和坚持西行。','people','回到人物群像'],['情节作用','倒马毒桩的作用是？',['让悟空只靠硬拼取胜','制造难题，推动悟空求助昴日星官','说明八戒害怕河水','帮助唐僧离开女儿国'],1,'毒桩使故事发生策略转折。','plot','回到关键镜头'],['人物群像','昴日星官的作用是？',['旁观者','蝎子精的克星，提供关键解法','女儿国的大臣','蝎子精同伙'],1,'他利用相克之理完成降妖。','people','回到人物群像'],['简答框架','人物分析最完整的答法是？',['只写性格词','具体行为→人物特点→情节结果','只复述妖精法术','只写结局'],1,'用情节证据支持人物判断。','exam','回到中考攻略']];
  const qtabs=document.getElementById('question-tabs'), stem=document.getElementById('stem'), options=document.getElementById('options'), feedback=document.getElementById('feedback'), review=document.getElementById('review-link'), progress=document.getElementById('question-progress'), layout=document.querySelector('.question-layout'); const showQ=i=>{const q=qs[i];stem.textContent=q[1];layout.style.backgroundImage=`url('${keyBase}${scenes[[0,7,13,16,19][i]][3]}.png')`;options.replaceChildren(...q[2].map((x,j)=>{const b=document.createElement('button');b.innerHTML=`<span class="opt-letter">${String.fromCharCode(65+j)}</span><span class="opt-text">${x}</span>`;b.onclick=()=>{[...options.children].forEach(n=>n.classList.remove('is-correct','is-wrong'));const ok=j===q[3];b.classList.add(ok?'is-correct':'is-wrong');feedback.textContent=`${ok?'回答正确。':'再想一想。'}${q[4]}`;review.classList.toggle('is-visible',!ok);review.textContent=q[6];review.onclick=()=>openTopic(q[5]);};return b;}));progress.textContent=`第 ${i+1} / 5 题`;[...qtabs.children].forEach((b,j)=>b.classList.toggle('is-active',j===i));feedback.textContent='选择一个选项后查看解析。';review.classList.remove('is-visible');}; qtabs.replaceChildren();qs.forEach((q,i)=>{const b=document.createElement('button');b.textContent=`${String(i+1).padStart(2,'0')} ${q[0]}`;b.onclick=()=>showQ(i);qtabs.appendChild(b);});showQ(0);
})();
