(() => {
  const base = 'https://wulikeshihua-1339740714.cos.ap-beijing.myqcloud.com/%E8%AF%AD%E6%96%87/assets/media/journey/lessons/';
  const keyBase = `${base}xiyouji_12_key_shots/`;
  const legacyPortraitBase = `${base}xiyouji_06_portraits/`;
  const portraitBase = `${base}xiyouji_12_portraits/`;
  document.title = '三调芭蕉扇 · 名著精学';
  document.body.style.background = `linear-gradient(135deg,rgba(10,25,28,.55),rgba(4,10,12,.78)),url('${keyBase}01-fire-mountain-blocks-road.png') center/cover no-repeat fixed`;
  document.querySelector('.eyebrow').textContent = '西游记 · 第 59—61 回 · 名著精学';
  document.querySelector('h1').textContent = '三调芭蕉扇';
  document.getElementById('story-video-trigger').style.display = 'none';
  document.getElementById('story-video-modal').hidden = true;
  const tabs = [...document.querySelectorAll('.tabs button')], topics = [...document.querySelectorAll('.topic')];
  const openTopic = id => { topics.forEach(topic => topic.classList.toggle('is-active', topic.id === id)); tabs.forEach(tab => tab.classList.toggle('is-active', tab.dataset.topic === id)); };
  tabs.forEach(tab => tab.addEventListener('click', () => openTopic(tab.dataset.topic)));

  const pages = [
    ['火焰山阻路', '师徒西行来到火焰山，只见烈焰冲天，山路不能通行。当地人说，唯有芭蕉扇能熄灭此火。', '火焰山先把“西行”变成一个无法硬闯的现实难题。芭蕉扇既是道具，也是情节的目标：悟空后面的三次借扇，都是围绕怎样获得并正确使用它展开。'],
    ['一调被扇', '悟空到芭蕉洞向铁扇公主借扇。铁扇公主因红孩儿一事怀恨，举扇便把悟空扇得无影无踪。', '第一次借扇失败，原因不是悟空不够勇敢，而是没有看清对方的情感立场。铁扇公主的仇怨让“讲理借物”无法奏效，悟空必须调整准备。'],
    ['二调得假', '悟空得了定风丹，再到洞前不怕扇风；他化作小虫进入铁扇公主腹中，迫使她交出一把扇子。', '第二次看似成功，却只得到假扇。这里提示读者：取得物品不等于解决问题，必须用结果检验真假；悟空的策略已变得灵活，却还没有辨清对手的反制。'],
    ['三调斗智', '悟空发现假扇无效，又遇牛魔王变作悟空骗走真扇。悟空识破后与牛魔王斗法，众神也来相助。', '第三次的关键是“斗智与协作”。牛魔王、铁扇公主、红孩儿是一家，家庭关系解释了冲突根源；悟空必须识破变身、联动外援，才拿回真扇。'],
    ['真扇灭火', '牛魔王受伏，铁扇公主交出真芭蕉扇。悟空连扇三次，火焰山烈火熄灭，师徒终于跨山西行。', '结局把“三调”收束为完整因果链：受阻、失败、受骗、识破、得真扇、灭火。答题时不能笼统说“悟空借到扇子”，要写清每次策略和结果。'],
  ];
  const reading = document.getElementById('reading'), readingImage = reading.querySelector('.scene-image-frame img');
  readingImage.src = `${base}xiyouji_12_reading_storyboard.png`;
  readingImage.alt = '三调芭蕉扇五幕连环图';
  const copy = reading.querySelector('.reading-copy');
  copy.innerHTML = '<div class="reading-pager-top"><div class="reading-mode-switch"><button class="is-active" data-mode="both">对照</button><button data-mode="old">原文</button><button data-mode="new">白话</button></div><span class="reading-progress"></span></div><section class="reading-page"></section><div class="reading-pager-bottom"><button class="reading-nav" data-move="-1">←</button><div class="reading-stage-dots"></div><button class="reading-nav" data-move="1">→</button></div>';
  let pageIndex = 0, readingMode = 'both';
  const renderReading = () => { const [title, original, modern] = pages[pageIndex], panels = []; if (readingMode !== 'new') panels.push(`<article class="reading-panel"><h3>情节原貌 · ${title}</h3><p>${original}</p></article>`); if (readingMode !== 'old') panels.push(`<article class="reading-panel"><h3>白话精读 · ${title}</h3><p>${modern}</p></article>`); copy.querySelector('.reading-page').innerHTML = panels.join(''); copy.querySelector('.reading-page').classList.toggle('is-single', panels.length === 1); copy.querySelector('.reading-progress').textContent = `${String(pageIndex + 1).padStart(2, '0')} / 05`; copy.querySelector('.reading-stage-dots').innerHTML = pages.map((item,index) => `<button class="reading-stage-dot${index === pageIndex ? ' is-active' : ''}" data-page="${index}" title="${item[0]}"></button>`).join(''); copy.querySelectorAll('[data-mode]').forEach(button => button.classList.toggle('is-active',button.dataset.mode === readingMode)); copy.querySelectorAll('[data-move]').forEach(button => button.disabled = (Number(button.dataset.move) < 0 && pageIndex === 0) || (Number(button.dataset.move) > 0 && pageIndex === 4)); };
  copy.addEventListener('click', event => { const button = event.target.closest('button'); if (!button) return; if (button.dataset.mode) readingMode = button.dataset.mode; if (button.dataset.page !== undefined) pageIndex = Number(button.dataset.page); if (button.dataset.move) pageIndex = Math.max(0,Math.min(4,pageIndex + Number(button.dataset.move))); renderReading(); });
  renderReading();

  const groups = [['block','01 火焰阻路','火焰山先制造无法通行的难题，悟空必须寻找正确工具。'],['first','02 一二调扇','第一次被扇走，第二次以定风丹和变身取扇，却得到假扇。'],['third','03 三调斗智','牛魔王变身骗扇，悟空识破后与之斗智斗法。'],['win','04 降牛灭火','众神协力收伏牛魔王，真扇到手，烈火熄灭。'],['road','05 重返西行','师徒跨过火焰山，回到共同的取经道路。']];
  const scenes = [
    ['block','火焰阻路','火焰山挡住西路','01-fire-mountain-blocks-road','烈焰使师徒不能硬闯，借扇任务由此开始。'],['block','乡人指路','得知芭蕉扇传说','02-villagers-explain-fire','当地人的说明交代了破局工具和前往芭蕉洞的方向。'],['block','悟空寻扇','前往芭蕉洞求助','03-wukong-seeks-fan','悟空先以借物方式解决难题，符合他主动破局的特点。'],['block','公主拒借','铁扇公主守住洞门','04-princess-refuses-fan','红孩儿的旧事使借扇从普通求助变成有情感根源的冲突。'],
    ['first','一扇飞走','芭蕉扇把悟空扇飞','05-first-fan-blast','第一次失败说明只靠勇气与口头请求不能解决问题。'],['first','借得定风','悟空准备定风丹','06-wukong-borrows-wind-fixing-bead','悟空先补足对手的优势，再开始第二次尝试。'],['first','再到洞前','定风而立请求借扇','07-second-request-fan','策略从硬受扇风转为有准备地正面周旋。'],['first','化虫入腹','悟空以变身取扇','08-wukong-becomes-insect','悟空把正面冲突转为斗智，逼得铁扇公主暂时交扇。'],['first','腹内降服','铁扇公主交出扇子','09-wukong-inside-princess','第二次获得扇子只是阶段胜利，真假仍需由实际效果验证。'],['first','假扇无功','假扇反使火势更盛','10-false-fan-fails','结果揭穿假扇，故事出现新的反转。'],
    ['third','八戒提醒','追查真扇去向','11-bajie-reveals-cattle-king','同伴信息帮助悟空把目光转向牛魔王。'],['third','相逢牛王','悟空正面质问牛魔王','12-wukong-meets-bull-king','牛魔王是本回更强的阻力，也把家庭关系带入冲突。'],['third','假悟空骗扇','牛魔王变身取走真扇','13-bull-king-becomes-wukong','变身骗局与真假辨析形成新的斗智考点。'],['third','悟空识破','悟空发现牛王诡计','14-wukong-discovers-trick','悟空不被表象迷惑，及时追查真扇。'],['third','斗法开场','悟空牛王大战火山','15-magic-battle-begins','冲突升级，单靠一人难以收束，需引入协作。'],['third','牛王变牛','牛魔王显出巨牛身','16-bull-king-transforms','变形显示牛魔王的顽强，也推动天界援手到来。'],
    ['win','天兵相助','众神合力围困牛王','17-heavenly-allies-arrive','悟空善借外援，团队协作成为第三次成功的条件。'],['win','牛王受伏','真芭蕉扇归还','18-bull-king-subdued','牛魔王受伏后，取得真扇的障碍终于清除。'],['win','三扇灭火','悟空扇灭火焰山','19-true-fan-extinguishes-fire','真扇经过实际验证，三扇灭火是情节收束的关键动作。'],
    ['road','跨山西行','师徒穿过火焰山','20-team-crosses-fire-mountain','难题解决，故事回到取经主线。'],
  ];
  const plot = document.getElementById('plot'); plot.innerHTML = '<div class="story-groups"></div><div class="plot-layout"><div class="scene-art"><img></div><article class="scene-copy"><div class="group-detail"></div><h3></h3><p></p><ul></ul></article></div><div class="scene-selector"></div>';
  let activeGroup = 'block';
  const showScene = index => { const scene = scenes[index], image = plot.querySelector('.scene-art img'); image.src = `${keyBase}${scene[3]}.png`; image.alt = scene[2]; plot.querySelector('h3').textContent = scene[2]; plot.querySelector('.scene-copy p').textContent = scene[4]; plot.querySelector('ul').innerHTML = `<li><b class="highlight">情节作用：</b>${scene[4]}</li><li><b class="highlight">策略变化：</b>从直接借扇到斗智辨真，再到协作破局。</li><li><b class="highlight">中考方向：</b>复述“三调”时写清每次结果不同。</li>`; plot.querySelectorAll('[data-scene]').forEach(button => button.classList.toggle('is-active',Number(button.dataset.scene) === index)); };
  const renderPlot = () => { const group = groups.find(item => item[0] === activeGroup), list = scenes.map((scene,index) => ({scene,index})).filter(item => item.scene[0] === activeGroup); plot.querySelector('.story-groups').innerHTML = groups.map(item => `<button class="${item[0] === activeGroup ? 'is-active' : ''}" data-group="${item[0]}"><b>${item[1]}</b></button>`).join(''); plot.querySelector('.group-detail').textContent = group[2]; plot.querySelector('.scene-selector').innerHTML = list.map(({scene,index}) => `<button data-scene="${index}"><span>${String(index+1).padStart(2,'0')} / 20</span><b>${scene[1]}</b></button>`).join(''); showScene(list[0].index); };
  plot.addEventListener('click', event => { const button = event.target.closest('button'); if (!button) return; if (button.dataset.group) { activeGroup = button.dataset.group; renderPlot(); } else if (button.dataset.scene !== undefined) showScene(Number(button.dataset.scene)); }); renderPlot();

  const person = (src,name,role,traits,detail) => `<article class="person"><div class="portrait"><img src="${src}" alt="${name}人物群像"></div><div class="person-copy"><p class="person-role"><b>${name}</b><span>${role}</span></p><div class="traits">${traits}</div><p>${detail}</p></div></article>`;
  document.getElementById('people').innerHTML = `<div class="relationship-map"><article class="relationship-card"><span>借扇冲突</span><b>孙悟空 × 铁扇公主</b><p>一调被拒、二调得假，冲突既有借扇目标，也有红孩儿旧怨。</p></article><article class="relationship-card core"><span>家庭线索</span><b>铁扇公主 × 牛魔王</b><p>二人是红孩儿父母；这层关系解释为何借扇会演变成更大斗法。</p></article><article class="relationship-card"><span>破局协作</span><b>孙悟空 × 众神</b><p>第三次识破牛魔王后，借助外援收伏强敌，获得真扇。</p></article></div><div class="people-grid">${person(`${legacyPortraitBase}sun-wukong.png`,'孙悟空','破局者 · 策略者','<span class="trait-core">机智勇敢</span><span class="trait-action">三次调扇</span>','他失败后会调整策略：先定风、再辨假、后借外援，体现<b class="highlight">不服输与善应变</b>。')}${person(`${legacyPortraitBase}tang-sanzang.png`,'唐三藏','取经人 · 目标守护者','<span class="trait-core">坚定西行</span><span class="trait-action">受阻待援</span>','火焰山阻住的是全队的西行路，他让“借扇”始终指向完成取经使命。')}${person(`${legacyPortraitBase}zhu-bajie.png`,'猪八戒','同伴 · 信息助力者','<span class="trait-core">忠于师父</span><span class="trait-action">协力追扇</span>','他参与追查与助战，使借扇不只是悟空单人的冒险。')}${person(`${portraitBase}princess-iron-fan.png`,'铁扇公主','持扇者 · 护家者','<span class="trait-core">刚烈</span><span class="trait-flaw">怀恨</span>','她因红孩儿受伏而不愿借扇，人物行为要联系家庭情感，不能简单写成“故意作恶”。')}${person(`${portraitBase}bull-demon-king.png`,'牛魔王','阻扇者 · 善变者','<span class="trait-core">本领强大</span><span class="trait-flaw">狡猾护家</span>','他变作悟空骗回真扇，使第三次借扇升级为真假、斗智与协作的较量。')}</div>`;

  const exam = document.getElementById('exam');
  exam.innerHTML = '<div class="exam-grid"><article class="exam-card answer-card"><h3>情节题答案搭建器</h3><div class="answer-builder"><div class="answer-step"><span>01 起因</span><b>火焰阻路</b><p>先点明为何借扇。</p></div><div class="answer-step"><span>02 三次策略</span><b>失败、得假、斗智</b><p>分别写清变化。</p></div><div class="answer-step"><span>03 关键证据</span><b>真扇三灭火</b><p>用动作证明结果。</p></div><div class="answer-step"><span>04 落点</span><b>跨山西行</b><p>回到取经主线。</p></div></div><p class="formula"><b>完整答案：</b>师徒被火焰山阻住西路，孙悟空向铁扇公主三次借芭蕉扇：第一次因旧怨被扇走，第二次用定风丹、变身取到的却是假扇，第三次识破牛魔王变身骗扇并在众神相助下取得真扇；他连扇三次灭火，师徒才得以跨山西行。</p><div class="answer-evidence"><section class="evidence-board"><h4>把答案写实：三次调扇定位</h4><div class="evidence-list"><div><b>一调失败</b><span>铁扇公主因红孩儿旧事怀恨，一扇将悟空扇走。</span></div><div><b>二调得假</b><span>悟空定风、变身取扇，但假扇反而助长火势。</span></div><div><b>三调成功</b><span>识破牛魔王骗局，协力取回真扇，三扇灭火。</span></div></div></section><aside class="answer-checklist"><h4>落笔前自检</h4><p>交代火焰山阻路</p><p>区分三次结果</p><p>写出真假扇转折</p><p>补足灭火西行</p></aside></div></article><article class="exam-card avoid-card"><h3>高频题与易失分</h3><div class="exam-types"><div class="exam-type"><b>情节概括</b><p>不能只写“借扇”，必须区分一调、二调、三调的结果。</p></div><div class="exam-type"><b>人物形象</b><p>悟空的机智来自失败后的策略调整，而非只会斗法。</p></div><div class="exam-type"><b>关系辨析</b><p>铁扇公主、牛魔王、红孩儿是一家，关系解释借扇冲突。</p></div><div class="exam-type"><b>作用分析</b><p>假扇使第二次“得到”变成反转，推动第三次斗智。</p></div></div><ul><li>铁扇公主交出的第二把扇是假扇，不要把它写成最终灭火的真扇。</li><li>牛魔王变作悟空骗走真扇，不能把骗扇者误写成铁扇公主。</li><li>“三扇灭火”写的是拿到真扇后的结果，不是三次借扇本身。</li></ul><div class="exam-review"><section class="review-item"><span>考场 30 秒</span><b>先数三调</b><p>第一被扇走，第二得假扇，第三获真扇。</p></section><section class="review-item"><span>答题核心</span><b>策略在前</b><p>先写悟空怎样调整，再写人物机智与担当。</p></section><section class="review-item"><span>最后检查</span><b>结果写全</b><p>真扇三灭火，师徒跨山继续西行。</p></section></div></article></div>';

  const questions = [
    ['情节顺序','下列哪一项最符合“三调芭蕉扇”的因果链？',['火焰阻路—一调被扇—二调得假—三调斗智—真扇灭火','真扇灭火—火焰阻路—牛魔王骗扇','红孩儿放火—观音收伏—三调芭蕉扇','一调得真扇—二调灭火—三调西行'],0,'三次调扇的结果依次是失败、得假、得真，最后才灭火。','plot','回到关键镜头'],['人物关系','铁扇公主、牛魔王与红孩儿的关系是？',['师徒关系','三人是一家，铁扇公主和牛魔王是红孩儿父母','三人互不相识','红孩儿是悟空弟子'],1,'家庭关系说明铁扇公主为何因红孩儿一事不愿借扇。','people','回到人物群像'],['情节转折','第二次借到扇子后，为什么故事没有结束？',['悟空把扇子丢了','那是一把假扇，不能灭火，反而使火势更盛','唐僧不愿过火焰山','牛魔王已经被收伏'],1,'道具真假必须由结果验证，假扇推动第三次斗智。','plot','回到关键镜头'],['人物理解','孙悟空在本回最突出的品质是？',['只会硬拼','失败后调整策略、辨别真假并善借外援','畏惧火焰山','放弃保护师父'],1,'从定风、变身、识破骗局到请援，能看出他的机智担当。','exam','回到中考攻略'],['简答框架','概括“三调芭蕉扇”时最完整的写法是？',['只写悟空借到扇子','起因—三次策略与不同结果—真扇灭火—师徒西行','只写牛魔王会变身','只写火焰山很热'],1,'情节概括要抓住每一次调扇的变化和最后的因果收束。','exam','回到中考攻略']];
  const questionImages = ['01-fire-mountain-blocks-road.png','04-princess-refuses-fan.png','10-false-fan-fails.png','14-wukong-discovers-trick.png','20-team-crosses-fire-mountain.png'];
  const qtabs = document.getElementById('question-tabs'), stem = document.getElementById('stem'), options = document.getElementById('options'), feedback = document.getElementById('feedback'), review = document.getElementById('review-link'), progress = document.getElementById('question-progress'), layout = document.querySelector('.question-layout');
  const showQuestion = index => { const question = questions[index]; stem.textContent = question[1]; layout.style.backgroundImage = `url('${keyBase}${questionImages[index]}')`; layout.style.backgroundSize = 'cover'; layout.style.backgroundPosition = 'center'; options.replaceChildren(...question[2].map((option,optionIndex) => { const button = document.createElement('button'); button.type = 'button'; button.innerHTML = `<span class="opt-letter">${String.fromCharCode(65+optionIndex)}</span><span class="opt-text">${option}</span>`; button.addEventListener('click',() => { [...options.children].forEach(item => item.classList.remove('is-selected','is-correct','is-wrong')); const correct = optionIndex === question[3]; button.classList.add('is-selected',correct ? 'is-correct' : 'is-wrong'); feedback.textContent = `${correct ? '回答正确。' : '再想一想。'}${question[4]}`; review.classList.toggle('is-visible',!correct); if (!correct) { review.textContent = question[6]; review.onclick = () => openTopic(question[5]); } }); return button; })); progress.textContent = `第 ${index+1} / ${questions.length} 题`; [...qtabs.children].forEach((button,tabIndex) => button.classList.toggle('is-active',tabIndex === index)); feedback.textContent = '选择一个选项后查看解析。'; review.classList.remove('is-visible'); };
  qtabs.replaceChildren(); questions.forEach((question,index) => { const button = document.createElement('button'); button.type = 'button'; button.textContent = `${String(index+1).padStart(2,'0')} ${question[0]}`; button.addEventListener('click',() => showQuestion(index)); qtabs.appendChild(button); }); showQuestion(0);
})();
